
on:
- push
- workflow_dispatch

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.4.2
    - name: build container image
      shell: bash
      run: docker build -t pythonapp:latest .
    - name: Install Trivy
      shell: bash
      run: 
         wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
         sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
    - name: Scan Image
      shell: bash
      run: trivy image pythonapp:latest

  
