
on:
- push
- workflow_dispatch

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.4.2
    - name: build container image
      shell: bash
      run: docker build -t pythonapp:latest .
    - name: Install Trivy
      shell: bash
      run: sh install.sh
    - name: Scan Image
      shell: bash
      run: trivy image pythonapp:latest

  
