
on:
- push
- workflow_dispatch

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.4.2
    - shell: bash
      run: docker build -t pythonapp:latest .
  
